import * as THREE from 'three';
type Piece={mesh:THREE.Mesh; velocity:THREE.Vector3; spin:THREE.Vector3; life:number};
export class Bot { readonly group=new THREE.Group(); readonly position=new THREE.Vector3(); readonly deathGroup=new THREE.Group(); hp=100;alive=true;cooldown=0; private parts:THREE.Mesh[]=[];private arms:THREE.Mesh[]=[];private legs:THREE.Mesh[]=[];private pieces:Piece[]=[];private walk=0;private reaction=0;private gun:THREE.Mesh;
  constructor(public id:string,public name:string,private color:number){const mat=new THREE.MeshBasicMaterial({color});const add=(geo:THREE.BufferGeometry,x:number,y:number,z:number,kind:'arm'|'leg'|'body'='body')=>{const m=new THREE.Mesh(geo,mat);m.position.set(x,y,z);this.group.add(m);this.parts.push(m);if(kind==='arm')this.arms.push(m);if(kind==='leg')this.legs.push(m);return m;};add(new THREE.BoxGeometry(.68,.82,.38),0,1.22,0);add(new THREE.BoxGeometry(.52,.52,.52),0,1.92,0);add(new THREE.BoxGeometry(.16,.58,.16),-.48,1.32,0,'arm');add(new THREE.BoxGeometry(.16,.58,.16),.48,1.32,0,'arm');add(new THREE.BoxGeometry(.19,.67,.19),-.22,.46,0,'leg');add(new THREE.BoxGeometry(.19,.67,.19),.22,.46,0,'leg');this.gun=new THREE.Mesh(new THREE.BoxGeometry(.14,.14,.72),new THREE.MeshBasicMaterial({color:0x18202e}));this.gun.position.set(.34,1.38,-.28);this.gun.rotation.x=-.22;this.group.add(this.gun);}
  muzzlePosition(){const p=new THREE.Vector3(.34,1.38,-.7);return this.group.localToWorld(p);}
  respawn(x:number,z:number){this.position.set(x,0,z);this.group.position.copy(this.position);this.hp=100;this.alive=true;this.group.visible=true;this.deathGroup.visible=false;this.pieces=[];}
  damage(n:number){this.hp=Math.max(0,this.hp-n);this.reaction=.16;if(!this.hp)this.die();}
  private die(){this.alive=false;this.group.visible=false;this.deathGroup.clear();this.deathGroup.position.copy(this.position);this.deathGroup.visible=true;this.pieces=this.parts.map((part,i)=>{const m=new THREE.Mesh(part.geometry,(part.material as THREE.Material).clone());m.position.copy(part.position);m.rotation.copy(part.rotation);this.deathGroup.add(m);return{mesh:m,velocity:new THREE.Vector3((Math.random()-.5)*3,2+Math.random()*2,(Math.random()-.5)*3),spin:new THREE.Vector3(Math.random()*8,Math.random()*8,Math.random()*8),life:1.1+i*.02};});}
  updateVisual(dt:number,moving:boolean,aiming:boolean){if(!this.alive){for(const p of this.pieces){p.life-=dt;p.velocity.y-=11*dt;p.mesh.position.addScaledVector(p.velocity,dt);p.mesh.rotation.x+=p.spin.x*dt;p.mesh.rotation.y+=p.spin.y*dt;p.mesh.rotation.z+=p.spin.z*dt;p.mesh.visible=p.life>0;}return;}this.walk+=moving?dt*10:dt*3;const swing=moving?Math.sin(this.walk)*.55:0;this.legs.forEach((l,i)=>l.rotation.x=(i?1:-1)*swing);this.arms.forEach((a,i)=>a.rotation.x=(aiming?-.72:0)+(i?1:-1)*swing*.45);if(this.reaction>0){this.reaction-=dt;this.group.rotation.z=Math.sin(this.reaction*90)*.13;}else this.group.rotation.z=0;}
}
