import { resolveShot, aimDirection, KillTracker, type Combatant, type ConfirmedHit, type PlannedHit, type ShotEvent } from '../../../shared/combat';
import { WeaponEffects } from '../systems/WeaponEffects';
import { BattleFeedback } from '../ui/BattleFeedback';
import { chooseWeaponPoint } from '../../../shared/spawns';
import { GameSettings } from '../ui/GameSettings';
import * as T from'three';import{InputManager}from'../input/InputManager';import{DesktopInput}from'../input/DesktopInput';import{MobileInput}from'../input/MobileInput';import{PerformanceManager}from'../systems/PerformanceManager';import{CollisionSystem}from'../systems/CollisionSystem';import{SpawnSystem}from'../systems/SpawnSystem';import{RespawnSystem}from'../systems/RespawnSystem';import{FreeForAllMode}from'../systems/GameMode';import{DamageFeedbackSystem}from'../systems/DamageFeedbackSystem';import{Arena}from'../world/Arena';import{Player}from'../player/Player';import{PlayerController}from'../player/PlayerController';import{Weapon}from'../weapons/Weapon';import{Bot}from'../enemies/Bot';import{BotAI}from'../enemies/BotAI';import{HUD}from'../ui/HUD';import{mobileMarkup}from'../ui/MobileControls';import{Armory}from'../ui/Armory';import{GameLoop}from'./GameLoop';import{ARENA_CAMERA_FAR,groundHeight}from'../../../shared/arena';import{WEAPON_IDS,WEAPON_SPECS,type WeaponId}from'../../../shared/weapons';
type Pickup={id:WeaponId;mesh:T.Mesh;position:T.Vector3;cooldown:number};
export class Game{
  private scene=new T.Scene();private cam=new T.PerspectiveCamera(75,1,.05,ARENA_CAMERA_FAR);private renderer:T.WebGLRenderer;private input=new InputManager();private arena=new Arena();private collision=new CollisionSystem(this.arena.boxes,(x,z)=>this.arena.groundHeight(x,z));private player=new Player();private controller=new PlayerController();private bots:Bot[]=[];private ai=new BotAI();private spawns=new SpawnSystem(this.arena.spawns);private respawn=new RespawnSystem();private weapons=new Map<WeaponId,Weapon>(WEAPON_IDS.map(id=>[id,new Weapon(WEAPON_SPECS[id])]));private active:WeaponId='ar';private owned=new Set<WeaponId>(['ar']);private pickups:Pickup[]=[];private hud:HUD;private armory:Armory;private feedback:DamageFeedbackSystem;private effects:WeaponEffects;private battle:BattleFeedback;private killTracker=new KillTracker('solo');private shotSequence=0;private elapsed=0;private status=new Map<string,{slowUntil:number;burn?:{attackerId:string;nextTick:number;expiresAt:number}}>();private statusTimer=0;private loop:GameLoop;private settings?:GameSettings;private desktop?:DesktopInput;private mobile?:MobileInput;private mode=new FreeForAllMode();private hit=0;private kill=0;private shake=0;private notice='';private noticeT=0;private gun=new T.Group();private gunFlash:T.Mesh;private dead=false;private killer='';private coarse=matchMedia('(pointer:coarse)').matches||navigator.maxTouchPoints>0;private resize=()=>{};
  private restorePointerLock=()=>{if(this.coarse||this.settings?.isOpen||document.pointerLockElement===this.root)return;try{this.root.requestPointerLock?.()?.catch(()=>{});}catch{/* The settings hint remains available when pointer lock fails. */}};
  constructor(private root:HTMLElement){const performance=new PerformanceManager();this.renderer=new T.WebGLRenderer({antialias:!this.coarse,powerPreference:'high-performance'});this.renderer.setPixelRatio(performance.pixelRatio);this.renderer.setClearColor(0x16b9dc);root.append(this.renderer.domElement);root.insertAdjacentHTML('beforeend','<div class="co-feedback"></div><div class="co-hud"></div>'+mobileMarkup());this.hud=new HUD(root.querySelector('.co-hud')!);this.armory=new Armory(root,id=>{if(this.owned.has(id)){this.active=id;this.armory.render(this.active);}},()=>this.owned,this.restorePointerLock);this.feedback=new DamageFeedbackSystem(root.querySelector('.co-feedback')!);this.scene.add(this.arena.group,new T.HemisphereLight(0xffffff,0x16b9dc,2));this.effects=new WeaponEffects(this.scene,this.coarse);this.battle=new BattleFeedback(root);this.makeGun();const colors=[0xff4e7a,0x36d8c4,0xf7ba4b,0xa777ff,0x50a6ff,0xff6b37,0x37caff,0x92e34f],names=['RED','BLUE','GREEN','YELLOW','PURPLE','ORANGE','CYAN','LIME'];colors.forEach((color,i)=>{const bot=new Bot('bot'+i,names[i],color);bot.respawn(...this.spawns.choose(this.bots,bot.id));this.bots.push(bot);this.scene.add(bot.group,bot.deathGroup);});this.player.respawn(this.spawns.choose(this.bots));WEAPON_IDS.filter(id=>id!=='ar').forEach(id=>this.addPickup(id));if(this.coarse)this.mobile=new MobileInput(root,this.input);else{this.desktop=new DesktopInput(root,this.input);root.onclick=event=>{if(!(event.target as HTMLElement).closest('.co-armory, [data-game-ui], button, input'))this.restorePointerLock();};}this.resize=()=>{this.cam.aspect=root.clientWidth/root.clientHeight;this.cam.updateProjectionMatrix();this.renderer.setSize(root.clientWidth,root.clientHeight,false);};window.addEventListener('resize',this.resize);this.resize();this.loop=new GameLoop(dt=>this.update(dt));this.settings=new GameSettings(root,()=>{this.desktop?.setEnabled(false);this.mobile?.setEnabled(false);this.armory.setEnabled(false);this.loop.stop();},requestLock=>{this.desktop?.setEnabled(true);this.mobile?.setEnabled(true);this.armory.setEnabled(true);this.loop.start();if(requestLock)this.restorePointerLock();},false);}
  private makeGun(){const body=new T.MeshBasicMaterial({color:0x202634}),hands=new T.MeshBasicMaterial({color:this.player.color}),barrel=new T.Mesh(new T.BoxGeometry(.18,.16,.9),body);barrel.position.set(.34,-.28,-.8);for(const[x,y,z,rotation]of[[.47,-.52,-.5,-.55],[.12,-.55,-.63,.42],[.37,-.43,-.74,0],[.17,-.42,-.86,0]]){const hand=new T.Mesh(new T.BoxGeometry(.18,.28,.18),hands);hand.position.set(x,y,z);hand.rotation.z=rotation;this.gun.add(hand);}this.gunFlash=new T.Mesh(new T.OctahedronGeometry(.08),new T.MeshBasicMaterial({color:0xffd45d}));this.gunFlash.position.set(.34,-.25,-1.3);this.gunFlash.visible=false;this.gun.add(barrel,this.gunFlash);this.cam.add(this.gun);this.scene.add(this.cam);}
  private pickupPoint(previous?:[number,number]){return chooseWeaponPoint([this.player,...this.bots].map(p=>({x:p.position.x,z:p.position.z,alive:p.alive})),this.pickups.filter(p=>p.mesh.visible).map(p=>({x:p.position.x,z:p.position.z})),previous);}
  private addPickup(id:WeaponId){const mesh=new T.Mesh(new T.OctahedronGeometry(.75),new T.MeshBasicMaterial({color:WEAPON_SPECS[id].color}));const point=this.pickupPoint();mesh.visible=!!point;if(point)mesh.position.set(point[0],groundHeight(...point)+.9,point[1]);this.scene.add(mesh);this.pickups.push({id,mesh,position:mesh.position.clone(),cooldown:point?0:.1});}
  private respawnPickup(p:Pickup){const point=this.pickupPoint([p.position.x,p.position.z]);if(!point){p.cooldown=.1;return;}p.position.set(point[0],groundHeight(...point)+.9,point[1]);p.mesh.position.copy(p.position);p.mesh.visible=true;}
  private resetInput(){this.desktop?.setEnabled(true);this.mobile?.reset();this.input.reset();}
  private actors():Combatant[]{return[{id:'player',x:this.player.position.x,y:this.player.position.y,z:this.player.position.z,yaw:this.player.yaw,alive:this.player.alive},...this.bots.map(b=>({id:b.id,x:b.position.x,y:b.position.y+1.65,z:b.position.z,yaw:b.group.rotation.y,alive:b.alive}))];}
  private actor(id:string){return id==='player'?this.player:this.bots.find(b=>b.id===id);}
  private actorName(id:string){return id==='player'?'YOU':this.bots.find(b=>b.id===id)?.name??id;}
  private damageActor(attackerId:string,hit:PlannedHit,weapon:WeaponId):ConfirmedHit|undefined{
    const target=this.actor(hit.targetId),attacker=this.actor(attackerId);if(!target?.alive||!attacker)return;
    const damage=Math.min(target.hp,hit.damage);target.damage(damage);const killed=!target.alive;
    if(hit.targetId==='player'){this.feedback.damage(damage,attacker.position,this.player.position,new T.Vector3(-Math.sin(this.player.yaw),0,-Math.cos(this.player.yaw)));if(killed){this.dead=true;this.resetInput();this.killer=this.actorName(attackerId);this.mode.onDeath();}}
    if(killed){this.status.delete(hit.targetId);this.respawn.kill(hit.targetId);if(attackerId==='player'){this.mode.onKill();this.kill=.3;}this.battle.kill(this.killTracker.record({id:attackerId,name:this.actorName(attackerId),alive:attacker.alive},{id:hit.targetId,name:this.actorName(hit.targetId)},weapon,hit.headshot,this.elapsed*1000));}
    return{...hit,damage,killed};
  }
  private shootActor(attackerId:string,weapon:WeaponId,origin:T.Vector3,direction:T.Vector3,muzzle:T.Vector3){
    const result=resolveShot(weapon,origin.toArray() as [number,number,number],direction.toArray() as [number,number,number],this.actors().filter(a=>a.id!==attackerId)),eventId=`solo:shot:${++this.shotSequence}`;
    const shot:ShotEvent={...result,eventId,id:attackerId,weapon,origin:origin.toArray() as [number,number,number],dir:direction.toArray() as [number,number,number]};
    this.effects.play(shot,muzzle);const confirmed:ConfirmedHit[]=[];
    for(const hit of result.hits){const actual=this.damageActor(attackerId,hit,weapon);if(!actual)continue;confirmed.push(actual);if(!actual.killed&&(weapon==='ice'||weapon==='flame')){const status=this.status.get(hit.targetId)??{slowUntil:0};if(weapon==='ice')status.slowUntil=this.elapsed+1.25;else status.burn={attackerId,nextTick:status.burn?.nextTick??this.elapsed+.25,expiresAt:this.elapsed+2};this.status.set(hit.targetId,status);}}
    if(attackerId==='player'&&confirmed.length){this.hit=.12;this.battle.hit({eventId,weapon,hits:confirmed});}
  }
  private fire(){
    this.cam.position.copy(this.player.position);this.cam.rotation.set(this.player.pitch,this.player.yaw,0,'YXZ');this.cam.updateMatrixWorld(true);
    this.shootActor('player',this.active,this.player.position.clone(),new T.Vector3(...aimDirection(this.player.yaw,this.player.pitch)),this.gunFlash.getWorldPosition(new T.Vector3()));this.shake=.035;
  }
  private updateStatuses(dt:number){
    this.statusTimer+=dt;const show=this.statusTimer>=.08;if(show)this.statusTimer=0;
    for(const [id,status] of this.status){const actor=this.actor(id);if(!actor?.alive){this.status.delete(id);continue;}
      while(status.burn&&status.burn.nextTick<=this.elapsed&&status.burn.nextTick<=status.burn.expiresAt){const attackerId=status.burn.attackerId;status.burn.nextTick+=.25;const actual=this.damageActor(attackerId,{targetId:id,damage:4,headshot:false,position:[actor.position.x,actor.position.y+(id==='player'?-.4:1.22),actor.position.z]},'flame');if(actual&&attackerId==='player')this.battle.hit({eventId:`solo:burn:${++this.shotSequence}`,weapon:'flame',hits:[actual]});if(!actor.alive)break;}
      if(status.burn&&this.elapsed>=status.burn.expiresAt)status.burn=undefined;
      if(show&&actor.alive&&(status.burn||status.slowUntil>this.elapsed))this.effects.status(actor.position.clone().add(new T.Vector3(0,id==='player'?-.4:1.22,0)),status.burn?'flame':'ice');
      if(!status.burn&&status.slowUntil<=this.elapsed)this.status.delete(id);
    }
  }
  private update(dt:number){this.elapsed+=dt;this.desktop?.update();this.updateStatuses(dt);const input=this.input.getState();if(input.switchWeapon){const id=WEAPON_IDS[input.switchWeapon-1];if(id&&this.owned.has(id))this.active=id;}const weapon=this.weapons.get(this.active)!;if(input.reload)weapon.reload();this.controller.update(this.player,input,dt,this.collision,(this.status.get('player')?.slowUntil??0)>this.elapsed?.65:1);if(!this.armory.isOpen&&weapon.update(dt,input.shoot&&this.player.alive).fired)this.fire();this.pickups.forEach(p=>{p.mesh.rotation.y+=dt*2;if(p.cooldown>0){p.cooldown-=dt;if(p.cooldown<=0)this.respawnPickup(p);}else if(this.player.position.distanceTo(p.position)<2){this.owned.add(p.id);this.active=p.id;p.cooldown=30;p.mesh.visible=false;this.notice=`取得 ${WEAPON_SPECS[p.id].label}`;this.noticeT=1.5;this.armory.render(this.active);}});
    const attackers=new Set(this.bots.filter(bot=>this.ai.canSee(bot,this.player,this.collision,38)).sort((a,b)=>a.position.distanceTo(this.player.position)-b.position.distanceTo(this.player.position)).slice(0,3).map(bot=>bot.id));
    this.bots.forEach(bot=>{const before=bot.position.clone();this.ai.update(bot,this.player,(this.status.get(bot.id)?.slowUntil??0)>this.elapsed?dt*.65:dt,this.collision,this.arena.waypoints,attackers.has(bot.id),hit=>{
      const origin=bot.position.clone().add(new T.Vector3(0,1.65,0)),target=this.player.position.clone().add(new T.Vector3(0,-.43,0));
      if(!hit)target.add(new T.Vector3((Math.random()<.5?-1:1)*(1.3+Math.random()),Math.random()*.5,0));
      this.shootActor(bot.id,'ar',origin,target.sub(origin).normalize(),bot.muzzlePosition());
    });bot.updateVisual(dt,bot.position.distanceToSquared(before)>.001,bot.alive&&this.player.alive);});
    this.respawn.update(dt,id=>{if(id==='player'){this.player.respawn(this.spawns.choose(this.bots));this.status.delete('player');this.resetInput();this.dead=false;}else{const bot=this.bots.find(x=>x.id===id);if(bot)bot.respawn(...this.spawns.choose([this.player,...this.bots.filter(x=>x!==bot)],bot.id));}});this.hit=Math.max(0,this.hit-dt);this.kill=Math.max(0,this.kill-dt);this.noticeT=Math.max(0,this.noticeT-dt);this.effects.update(dt);this.feedback.update(dt,this.player.hp);this.cam.position.copy(this.player.position);this.cam.rotation.set(this.player.pitch,this.player.yaw,0,'YXZ');this.gun.position.z=this.shake*2;this.gun.rotation.x=this.shake;this.shake=Math.max(0,this.shake-dt*.5);this.armory.render(this.active);this.hud.render({hp:this.player.hp,ammo:weapon.ammo,reserve:weapon.reserve,label:weapon.spec.label,notice:this.noticeT?this.notice:'',kills:this.mode.kills,deaths:this.mode.deaths,dead:this.dead,killer:this.killer,hit:this.hit>0,kill:this.kill>0,reloading:weapon.reloading});this.cam.updateMatrixWorld(true);this.battle.update(dt,this.cam);this.renderer.render(this.scene,this.cam);}
  start(){this.loop.start();}
  dispose(){this.settings?.dispose();this.root.onclick=null;this.loop.stop();window.removeEventListener('resize',this.resize);this.desktop?.dispose();this.mobile?.dispose();this.armory.dispose();this.effects.dispose();this.battle.dispose();this.status.clear();this.killTracker.reset();this.feedback.dispose();this.renderer.dispose();this.root.replaceChildren();}
}
