import * as T from 'three';
import type { Socket } from 'socket.io-client';
import { Arena } from '../world/Arena';
import { InputManager } from '../input/InputManager';
import { DesktopInput } from '../input/DesktopInput';
import { MobileInput } from '../input/MobileInput';
import { Player } from '../player/Player';
import { HUD } from '../ui/HUD';
import { Armory } from '../ui/Armory';
import { mobileMarkup } from '../ui/MobileControls';
import { GameLoop } from './GameLoop';
import { Bot } from '../enemies/Bot';
import { MuzzleFlash } from '../systems/MuzzleFlash';
import { BulletTracer } from '../systems/BulletTracer';
import { DamageFeedbackSystem } from '../systems/DamageFeedbackSystem';
import { PerformanceManager } from '../systems/PerformanceManager';
import { ARENA_BOUNDS, ARENA_CAMERA_FAR, stepPlayer } from '../../../shared/arena';
import { WEAPON_IDS, WEAPON_SPECS, type WeaponId } from '../../../shared/weapons';

type WeaponState=Record<WeaponId,{ammo:number;reloadUntil:number}>;
type Net={id:string;name:string;avatar:string;color:number;x:number;y:number;z:number;yaw:number;pitch:number;hp:number;alive:boolean;kills:number;deaths:number;activeWeapon:WeaponId;ownedWeapons:WeaponId[];weapons:WeaponState;slowUntil:number;ack:number};
type Pickup={id:WeaponId;x:number;z:number;available:boolean;respawnAt:number};
type Snapshot={serverTime:number;tick:number;players:Net[];pickups:Pickup[]};
type Command={seq:number;clientTime:number;moveX:number;moveY:number;lookX:number;lookY:number;jump:boolean;reload:boolean};
type Shot={id:string;origin:[number,number,number];dir:[number,number,number];weapon:WeaponId;impact?:[number,number,number];hitIds:string[]};

export class MultiplayerGame{
  private scene=new T.Scene();private cam=new T.PerspectiveCamera(75,1,.05,ARENA_CAMERA_FAR);private renderer:T.WebGLRenderer;
  private input=new InputManager();private arena=new Arena();private player=new Player();private avatars=new Map<string,Bot>();private pickupMeshes=new Map<WeaponId,T.Mesh>();
  private pending:Command[]=[];private snaps:Snapshot[]=[];private seq=0;private hud:HUD;private armory:Armory;private feedback:DamageFeedbackSystem;
  private flash:MuzzleFlash;private tracers:BulletTracer;private loop:GameLoop;private desktop?:DesktopInput;private mobile?:MobileInput;
  private resize=()=>{};private owned=new Set<WeaponId>(['ar']);private active:WeaponId='ar';private weapons:WeaponState=Object.fromEntries(WEAPON_IDS.map(id=>[id,{ammo:WEAPON_SPECS[id].magazine,reloadUntil:0}])) as WeaponState;
  private kills=0;private deaths=0;private dead=false;private killer='';private ping=0;private pingTimer=0;private serverClockOffset=0;private hasClockOffset=false;private notice='';private noticeT=0;
  private wasShooting=false;private lastLocalShot=0;private shake=0;private gun=new T.Group();private gunFlash:T.Mesh;private gunMaterial=new T.MeshBasicMaterial({color:0x202634});private handMaterial=new T.MeshBasicMaterial({color:0xffffff});private coarse=matchMedia('(pointer:coarse)').matches||navigator.maxTouchPoints>0;
  constructor(private root:HTMLElement,private socket:Socket,private roomCode:string|undefined,private onFatal:(reason:string)=>void){
    const performance=new PerformanceManager();this.renderer=new T.WebGLRenderer({antialias:!this.coarse,powerPreference:'high-performance'});this.renderer.setPixelRatio(performance.pixelRatio);this.renderer.setClearColor(0x16b9dc);root.append(this.renderer.domElement);
    root.insertAdjacentHTML('beforeend','<div class="co-feedback"></div><div class="co-hud"></div><div class="co-mp-roster"></div><div class="co-minimap" aria-label="戰術小地圖"></div>'+mobileMarkup());
    this.hud=new HUD(root.querySelector('.co-hud')!);this.feedback=new DamageFeedbackSystem(root.querySelector('.co-feedback')!);this.armory=new Armory(root,id=>this.socket.emit('match:weapon',id),()=>this.owned);
    this.scene.add(this.arena.group,new T.HemisphereLight(0xffffff,0x16b9dc,2));this.flash=new MuzzleFlash(this.scene);this.tracers=new BulletTracer(this.scene);this.makeGun();this.makePickups();
    if(this.coarse)this.mobile=new MobileInput(root,this.input);else{this.desktop=new DesktopInput(root,this.input);root.onclick=e=>{if(!(e.target as HTMLElement).closest('.co-armory'))root.requestPointerLock();};}
    this.resize=()=>{this.cam.aspect=root.clientWidth/root.clientHeight;this.cam.updateProjectionMatrix();this.renderer.setSize(root.clientWidth,root.clientHeight,false);};window.addEventListener('resize',this.resize);this.resize();
    this.socket.on('match:snapshot',this.onSnapshot);this.socket.on('match:shot',this.onShot);this.socket.on('match:damage',this.onDamage);this.socket.on('disconnect',this.onDisconnect);this.socket.on('connect_error',this.onConnectError);this.loop=new GameLoop(dt=>this.update(dt));
  }
  start(){this.loop.start();}
  private makeGun(){const barrel=new T.Mesh(new T.BoxGeometry(.18,.16,.9),this.gunMaterial);barrel.position.set(.34,-.28,-.8);const pieces:[[number,number,number],[number,number,number]][]=[[[.17,.48,.18],[.47,-.52,-.5]],[[.17,.43,.18],[.12,-.55,-.63]],[[.2,.18,.2],[.37,-.43,-.74]],[[.2,.18,.2],[.17,-.42,-.86]]];for(const[geo,pos]of pieces){const mesh=new T.Mesh(new T.BoxGeometry(...geo),this.handMaterial);mesh.position.set(...pos);this.gun.add(mesh);}this.gunFlash=new T.Mesh(new T.OctahedronGeometry(.08),new T.MeshBasicMaterial({color:0xffd45d}));this.gunFlash.position.set(.34,-.25,-1.3);this.gunFlash.visible=false;this.gun.add(barrel,this.gunFlash);this.cam.add(this.gun);this.scene.add(this.cam);}
  private makePickups(){for(const id of WEAPON_IDS.filter(id=>id!=='ar')){const spec=WEAPON_SPECS[id],mesh=new T.Mesh(new T.OctahedronGeometry(.75),new T.MeshBasicMaterial({color:spec.color}));mesh.visible=false;this.pickupMeshes.set(id,mesh);this.scene.add(mesh);}}
  private predict(command:Command,dt:number){const p={x:this.player.position.x,y:this.player.position.y,z:this.player.position.z,yaw:this.player.yaw,pitch:this.player.pitch,velocityY:this.player.velocityY,alive:this.player.alive};stepPlayer(p,command,dt);this.player.position.set(p.x,p.y,p.z);this.player.yaw=p.yaw;this.player.pitch=p.pitch;this.player.velocityY=p.velocityY;}
  private onSnapshot=(s:Snapshot)=>{if(!Array.isArray(s?.players)||!Array.isArray(s?.pickups))return this.onFatal('多人同步資料無效');this.snaps.push(s);while(this.snaps.length>12)this.snaps.shift();const me=s.players.find(p=>p.id===this.socket.id);if(!me)return;const correction=this.player.position.distanceTo(new T.Vector3(me.x,me.y,me.z));if(!this.player.alive&&me.alive||correction>1.5)this.player.position.set(me.x,me.y,me.z);this.player.hp=me.hp;this.player.alive=me.alive;this.player.yaw=me.yaw;this.player.pitch=me.pitch;this.handMaterial.color.setHex(me.color);this.active=me.activeWeapon;this.owned=new Set(me.ownedWeapons);this.weapons=me.weapons;this.kills=me.kills;this.deaths=me.deaths;this.dead=!me.alive;this.pending=this.pending.filter(c=>c.seq>me.ack);this.gunMaterial.color.setHex(WEAPON_SPECS[this.active].color);this.syncAvatars(s.players);this.syncPickups(s.pickups);this.armory.render(this.active);};
  private syncAvatars(players:Net[]){const ids=new Set(players.map(p=>p.id));for(const[id,a]of this.avatars)if(!ids.has(id)){this.scene.remove(a.group,a.deathGroup);this.avatars.delete(id);}for(const p of players){if(p.id===this.socket.id)continue;let avatar=this.avatars.get(p.id);if(!avatar){avatar=new Bot(p.id,p.name,p.color,p.avatar);this.avatars.set(p.id,avatar);this.scene.add(avatar.group,avatar.deathGroup);}if(p.alive&&!avatar.alive)avatar.respawn(p.x,p.z);if(!p.alive&&avatar.alive)avatar.damage(100);}}
  private syncPickups(pickups:Pickup[]){for(const p of pickups){const mesh=this.pickupMeshes.get(p.id);if(!mesh)continue;mesh.position.set(p.x,.9,p.z);mesh.visible=p.available;}}
  private onShot=(shot:Shot)=>{const origin=new T.Vector3(...shot.origin),spec=WEAPON_SPECS[shot.weapon],length=shot.impact?origin.distanceTo(new T.Vector3(...shot.impact)):spec.range,end=shot.impact?new T.Vector3(...shot.impact):origin.clone().add(new T.Vector3(...shot.dir).multiplyScalar(length));if(shot.id!==this.socket.id)this.flash.burst(origin);if(shot.weapon==='flame'){for(let i=0;i<4;i++)this.tracers.fire(origin,end.clone().add(new T.Vector3((Math.random()-.5)*1.2,(Math.random()-.5)*.6,(Math.random()-.5)*1.2)));}else this.tracers.fire(origin,end);if(shot.impact)this.explosion(new T.Vector3(...shot.impact),spec.color);for(const id of shot.hitIds)this.avatars.get(id)?.hit();};
  private explosion(at:T.Vector3,color:number){const mesh=new T.Mesh(new T.SphereGeometry(.6,8,6),new T.MeshBasicMaterial({color,transparent:true,opacity:.85}));mesh.position.copy(at);this.scene.add(mesh);let life=.25;const grow=()=>{life-=.016;mesh.scale.multiplyScalar(1.18);(mesh.material as T.MeshBasicMaterial).opacity=Math.max(0,life*4);if(life>0)requestAnimationFrame(grow);else{this.scene.remove(mesh);mesh.geometry.dispose();(mesh.material as T.Material).dispose();}};grow();}
  private onDamage=(d:{from:{x:number;z:number};hp:number;name:string;weapon:WeaponId})=>{this.player.hp=d.hp;this.killer=d.name;this.notice=`遭 ${d.name} 使用 ${WEAPON_SPECS[d.weapon]?.label??'武器'} 擊中`;this.noticeT=.8;this.feedback.damage(25,new T.Vector3(d.from.x,0,d.from.z),this.player.position,new T.Vector3(-Math.sin(this.player.yaw),0,-Math.cos(this.player.yaw)));};
  private onDisconnect=()=>this.onFatal('連線已中斷');private onConnectError=()=>this.onFatal('無法連線至遊戲伺服器');
  private measurePing(dt:number){this.pingTimer-=dt;if(this.pingTimer>0)return;this.pingTimer=1;const started=Date.now();this.socket.emit('net:ping',(serverTime:number)=>{this.ping=Date.now()-started;const offset=Date.now()-serverTime-this.ping/2;this.serverClockOffset=this.hasClockOffset?this.serverClockOffset*.8+offset*.2:offset;this.hasClockOffset=true;});}
  private update(dt:number){
    this.desktop?.update();this.measurePing(dt);const input=this.input.getState(),command:Command={seq:++this.seq,clientTime:Date.now(),moveX:input.moveX,moveY:input.moveY,lookX:input.lookX,lookY:input.lookY,jump:input.jump,reload:input.reload};this.pending.push(command);while(this.pending.length>120)this.pending.shift();this.predict(command,dt);this.socket.emit('match:input',command);
    if(input.switchWeapon){const id=WEAPON_IDS[input.switchWeapon-1];if(id&&this.owned.has(id))this.socket.emit('match:weapon',id);}
    const spec=WEAPON_SPECS[this.active],state=this.weapons[this.active],time=Date.now();if(input.shoot&&!this.armory.isOpen&&(!this.wasShooting||time-this.lastLocalShot>=spec.fireDelay*1000)&&state.ammo>0&&state.reloadUntil<=time){this.gunFlash.visible=true;this.shake=.035;navigator.vibrate?.(8);this.socket.emit('match:fire',{clientTime:command.clientTime,yaw:this.player.yaw,pitch:this.player.pitch});this.lastLocalShot=time;}this.wasShooting=input.shoot;
    const a=this.snaps[Math.max(0,this.snaps.length-2)],b=this.snaps[this.snaps.length-1];if(a&&b)for(const[id,avatar]of this.avatars){const p=a.players.find(x=>x.id===id),n=b.players.find(x=>x.id===id);if(!p||!n)continue;avatar.group.position.lerpVectors(new T.Vector3(p.x,p.y-1.65,p.z),new T.Vector3(n.x,n.y-1.65,n.z),.65);avatar.position.copy(avatar.group.position);avatar.updateVisual(dt,Math.abs(n.x-p.x)+Math.abs(n.z-p.z)>.02,true);}for(const mesh of this.pickupMeshes.values())mesh.rotation.y+=dt*2;
    this.noticeT=Math.max(0,this.noticeT-dt);this.flash.update(dt);this.tracers.update(dt);this.feedback.update(dt,this.player.hp);this.gunFlash.visible=this.gunFlash.visible&&Math.random()>.45;this.cam.position.copy(this.player.position);this.cam.rotation.set(this.player.pitch+(Math.random()-.5)*this.shake,this.player.yaw+(Math.random()-.5)*this.shake,0,'YXZ');this.shake=Math.max(0,this.shake-dt*.5);
    const reloading=state.reloadUntil>Date.now();this.hud.render({hp:this.player.hp,ammo:state.ammo,reserve:Infinity,label:spec.label,notice:this.noticeT?this.notice:'',kills:this.kills,deaths:this.deaths,dead:this.dead,killer:this.killer,hit:false,kill:false,reloading});const latest=this.snaps[this.snaps.length-1],roster=this.root.querySelector('.co-mp-roster')!;roster.innerHTML=`<b>${this.roomCode||'房間'} · ${Math.round(this.ping)}ms</b>${(latest?.players||[]).sort((x,y)=>y.kills-x.kills).map(p=>`<div><span>${p.name}</span><strong>${p.kills}/${p.deaths}</strong></div>`).join('')}`;const mini=this.root.querySelector('.co-minimap')!,mapX=(x:number)=>(x-ARENA_BOUNDS.minX)/(ARENA_BOUNDS.maxX-ARENA_BOUNDS.minX)*100,mapZ=(z:number)=>(z-ARENA_BOUNDS.minZ)/(ARENA_BOUNDS.maxZ-ARENA_BOUNDS.minZ)*100;mini.innerHTML=`<b>戰術地圖</b>${(latest?.players||[]).map(p=>`<i class="${p.id===this.socket.id?'me':'enemy'}" style="color:#${p.color.toString(16).padStart(6,'0')};left:${Math.max(2,Math.min(98,mapX(p.x)))}%;top:${Math.max(2,Math.min(98,mapZ(p.z)))}%">●</i>`).join('')}`;this.renderer.render(this.scene,this.cam);
  }
  dispose(){this.loop.stop();window.removeEventListener('resize',this.resize);this.socket.off('match:snapshot',this.onSnapshot);this.socket.off('match:shot',this.onShot);this.socket.off('match:damage',this.onDamage);this.socket.off('disconnect',this.onDisconnect);this.socket.off('connect_error',this.onConnectError);this.desktop?.dispose();this.mobile?.dispose();this.flash.dispose();this.tracers.dispose();this.feedback.dispose();this.handMaterial.dispose();this.gunMaterial.dispose();this.renderer.dispose();this.root.replaceChildren();}
}
