export const BIRD_TYPES = {
  basic: {
    id: "basic",
    name: "紅怒鳥",
    color: "#ff7755",
    radius: 18,
    abilityLabel: "無主動技能",
    trail: "#ff9f85",
  },
  split: {
    id: "split",
    name: "分裂藍鳥",
    color: "#4f8dff",
    radius: 17,
    abilityLabel: "點擊後分裂為 3 隻",
    trail: "#9ec0ff",
  },
  dash: {
    id: "dash",
    name: "加速黃鳥",
    color: "#ffd24f",
    radius: 16,
    abilityLabel: "點擊後高速衝刺",
    trail: "#ffe89a",
  },
  bomb: {
    id: "bomb",
    name: "黑爆鳥",
    color: "#24283e",
    radius: 19,
    abilityLabel: "點擊後原地爆炸",
    trail: "#737aa0",
  },
  boomerang: {
    id: "boomerang",
    name: "迴力綠鳥",
    color: "#45c97d",
    radius: 17,
    abilityLabel: "點擊後折返飛行",
    trail: "#8ce4b0",
  },
  pierce: {
    id: "pierce",
    name: "穿透銀鳥",
    color: "#ced6e5",
    radius: 16,
    abilityLabel: "短時間穿透木材",
    trail: "#ecf2ff",
  },
  hammer: {
    id: "hammer",
    name: "重鎚棕鳥",
    color: "#b78347",
    radius: 20,
    abilityLabel: "重力強化下砸",
    trail: "#e3bf8f",
  },
  freeze: {
    id: "freeze",
    name: "冰凍青鳥",
    color: "#67d6ff",
    radius: 17,
    abilityLabel: "凍結周圍方塊",
    trail: "#c9f3ff",
  },
  magnet: {
    id: "magnet",
    name: "磁吸紫鳥",
    color: "#b48cff",
    radius: 17,
    abilityLabel: "吸附附近物件",
    trail: "#ddc9ff",
  },
  guide: {
    id: "guide",
    name: "誘導白鳥",
    color: "#f5f8ff",
    radius: 16,
    abilityLabel: "短時間自動導引",
    trail: "#ffffff",
  },
  egg: {
    id: "egg",
    name: "下蛋桃鳥",
    color: "#ffc4b5",
    radius: 18,
    abilityLabel: "點擊下桃子蛋並彈起",
    trail: "#ffd9cf",
  },
};

export function getBirdType(id) {
  return BIRD_TYPES[id] ?? BIRD_TYPES.basic;
}
