export const SIDES = {
  player: "player",
  enemy: "enemy",
};

export const SIDE_LABELS = {
  [SIDES.player]: "玩家",
  [SIDES.enemy]: "AI",
};

export const BOARD_SIZE = { rows: 5, cols: 7 };
export const CASTLE_HP = 25;
export const STARTING_HAND = 5;
export const DRAW_PER_TURN = 2;
export const HAND_CAP = 9;
export const STARTING_MAX_RESOURCE = 2;
export const MAX_RESOURCE = 8;
export const SUMMON_ZONE_COLS = 2;

export const CARD_TYPES = {
  unit: "unit",
  building: "building",
  spell: "spell",
};

export const CARD_DEFS = {
  vanguard: {
    id: "vanguard",
    name: "盾衛新兵",
    type: CARD_TYPES.unit,
    cost: 2,
    atk: 1,
    hp: 3,
    move: 2,
    range: 1,
    icon: "🛡️",
    tone: "unit",
    summary: "便宜前排，能快速補位。",
  },
  scoutLancer: {
    id: "scoutLancer",
    name: "斥候槍兵",
    type: CARD_TYPES.unit,
    cost: 3,
    atk: 2,
    hp: 2,
    move: 2,
    range: 1,
    icon: "🗡️",
    tone: "unit",
    summary: "機動近戰，適合追擊薄血目標。",
  },
  arcArcher: {
    id: "arcArcher",
    name: "弧線弓手",
    type: CARD_TYPES.unit,
    cost: 3,
    atk: 1,
    hp: 2,
    move: 1,
    range: 2,
    icon: "🏹",
    tone: "unit",
    summary: "遠程支援，可隔格輸出。",
  },
  ironPike: {
    id: "ironPike",
    name: "鐵棘槍陣",
    type: CARD_TYPES.unit,
    cost: 4,
    atk: 3,
    hp: 3,
    move: 1,
    range: 1,
    icon: "🔱",
    tone: "unit",
    summary: "高攻前排，壓制中線。",
  },
  bulwark: {
    id: "bulwark",
    name: "重甲堡衛",
    type: CARD_TYPES.unit,
    cost: 4,
    atk: 2,
    hp: 5,
    move: 2,
    range: 1,
    icon: "🛡️",
    tone: "unit",
    summary: "耐打主坦，能穩定推進。",
  },
  frostArbalest: {
    id: "frostArbalest",
    name: "寒弩射手",
    type: CARD_TYPES.unit,
    cost: 5,
    atk: 2,
    hp: 3,
    move: 1,
    range: 3,
    icon: "❄️",
    tone: "unit",
    summary: "長射程單位，適合守塔反打。",
  },
  siegeRam: {
    id: "siegeRam",
    name: "攻城衝車",
    type: CARD_TYPES.unit,
    cost: 5,
    atk: 4,
    hp: 4,
    move: 1,
    range: 1,
    icon: "🐏",
    tone: "unit",
    summary: "慢速高攻，專門拆前排與城堡。",
  },
  dragonRider: {
    id: "dragonRider",
    name: "龍翼騎士",
    type: CARD_TYPES.unit,
    cost: 6,
    atk: 4,
    hp: 5,
    move: 2,
    range: 1,
    icon: "🐉",
    tone: "unit",
    summary: "中後期王牌，移動與傷害兼具。",
  },
  royalGuardian: {
    id: "royalGuardian",
    name: "王城守護者",
    type: CARD_TYPES.unit,
    cost: 6,
    atk: 3,
    hp: 7,
    move: 1,
    range: 1,
    icon: "👑",
    tone: "unit",
    summary: "超高血量，適合保護前線建築。",
  },
  ancientColossus: {
    id: "ancientColossus",
    name: "古代巨像",
    type: CARD_TYPES.unit,
    cost: 8,
    atk: 6,
    hp: 8,
    move: 1,
    range: 1,
    icon: "🗿",
    tone: "unit",
    summary: "終盤王牌，一擊足以改變戰線。",
  },
  wallNode: {
    id: "wallNode",
    name: "石牆節點",
    type: CARD_TYPES.building,
    cost: 2,
    atk: 0,
    hp: 4,
    move: 0,
    range: 0,
    icon: "🧱",
    tone: "building",
    summary: "防禦建築，可作為前線召喚點。",
  },
  wallGuard: {
    id: "wallGuard",
    name: "石牆小兵",
    type: CARD_TYPES.unit,
    cost: 0,
    atk: 1,
    hp: 1,
    move: 1,
    range: 1,
    icon: "⚔",
    tone: "unit",
    summary: "石牆在每個我方回合開始時免費生成的 1/1 士兵。",
  },
  boltTower: {
    id: "boltTower",
    name: "弩箭塔",
    type: CARD_TYPES.building,
    cost: 4,
    atk: 1,
    hp: 3,
    move: 0,
    range: 2,
    icon: "🏰",
    tone: "building",
    summary: "防守型建築，能遠程攻擊。",
  },
  sunMonolith: {
    id: "sunMonolith",
    name: "日曜方尖碑",
    type: CARD_TYPES.building,
    cost: 5,
    atk: 2,
    hp: 5,
    move: 0,
    range: 3,
    icon: "☀️",
    tone: "building",
    summary: "長射程建築，穩住前線召喚點。",
  },
  skyCitadel: {
    id: "skyCitadel",
    name: "天空要塞",
    type: CARD_TYPES.building,
    cost: 7,
    atk: 3,
    hp: 8,
    move: 0,
    range: 3,
    icon: "🏯",
    tone: "building",
    summary: "後期核心建築，兼具血量與火力。",
  },
  emberShot: {
    id: "emberShot",
    name: "餘燼射擊",
    type: CARD_TYPES.spell,
    cost: 2,
    damage: 2,
    icon: "🔥",
    tone: "spell",
    summary: "造成 2 點傷害，可打單位或城堡。",
  },
  meteorVolley: {
    id: "meteorVolley",
    name: "流星齊射",
    type: CARD_TYPES.spell,
    cost: 5,
    damage: 4,
    icon: "☄️",
    tone: "spell",
    summary: "造成 4 點傷害，中期清場王牌。",
  },
  doomCannon: {
    id: "doomCannon",
    name: "末日砲擊",
    type: CARD_TYPES.spell,
    cost: 7,
    damage: 6,
    icon: "💥",
    tone: "spell",
    summary: "造成 6 點傷害，終盤收頭用法術。",
  },
};

export const STARTER_DECK = [
  ["vanguard", 4],
  ["scoutLancer", 3],
  ["arcArcher", 3],
  ["ironPike", 3],
  ["bulwark", 3],
  ["frostArbalest", 2],
  ["siegeRam", 2],
  ["dragonRider", 2],
  ["royalGuardian", 2],
  ["ancientColossus", 1],
  ["wallNode", 3],
  ["boltTower", 2],
  ["sunMonolith", 2],
  ["skyCitadel", 1],
  ["emberShot", 3],
  ["meteorVolley", 2],
  ["doomCannon", 1],
];
