import { InputManager } from './InputManager';
export class MobileInput {
  private joyId:number|null=null; private lookId:number|null=null; private shootId:number|null=null; private ox=0; private oy=0; private lx=0; private ly=0;
  private down=(e:PointerEvent)=>{ const r=this.el.getBoundingClientRect(); const control=e.target instanceof HTMLElement?e.target.closest('[data-fire],[data-jump],[data-reload],[data-weapon]'):null; if(e.clientX<r.left+r.width*.48&&!this.joyId){this.joyId=e.pointerId;this.ox=e.clientX;this.oy=e.clientY;} else if(control?.matches('[data-fire]')){this.shootId=e.pointerId;this.input.set({shoot:true});} else if(!control&&!this.lookId){this.lookId=e.pointerId;this.lx=e.clientX;this.ly=e.clientY;} this.el.setPointerCapture?.(e.pointerId); };
  private move=(e:PointerEvent)=>{if(e.pointerId===this.joyId){const dx=Math.max(-52,Math.min(52,e.clientX-this.ox)),dy=Math.max(-52,Math.min(52,e.clientY-this.oy));this.input.set({moveX:dx/52,moveY:-dy/52});this.el.style.setProperty('--joy-x',`${dx}px`);this.el.style.setProperty('--joy-y',`${dy}px`);} if(e.pointerId===this.lookId){this.input.addLook(e.clientX-this.lx,e.clientY-this.ly);this.lx=e.clientX;this.ly=e.clientY;}};
  private up=(e:PointerEvent)=>{if(e.pointerId===this.joyId){this.joyId=null;this.input.set({moveX:0,moveY:0});this.el.style.setProperty('--joy-x','0px');this.el.style.setProperty('--joy-y','0px');}if(e.pointerId===this.lookId)this.lookId=null;if(e.pointerId===this.shootId){this.shootId=null;this.input.set({shoot:false});}};
  constructor(private el:HTMLElement,private input:InputManager){el.addEventListener('pointerdown',this.down);el.addEventListener('pointermove',this.move);el.addEventListener('pointerup',this.up);el.addEventListener('pointercancel',this.up);}
  dispose(){this.el.removeEventListener('pointerdown',this.down);this.el.removeEventListener('pointermove',this.move);this.el.removeEventListener('pointerup',this.up);this.el.removeEventListener('pointercancel',this.up);}
}
