import express from 'express';
import {createServer} from 'http';
import {Server} from 'socket.io';
import {ARENA_SPAWNS,blocked,stepPlayer,type SimInput} from '../../shared/arena.js';
type Input=SimInput&{seq:number;clientTime:number;shoot?:boolean;reload?:boolean};
type P={id:string;name:string;color:number;x:number;y:number;z:number;yaw:number;pitch:number;velocityY:number;hp:number;alive:boolean;kills:number;deaths:number;ammo:number;reserve:number;reloadUntil:number;lastShot:number;lastSeq:number;input:Input};
type History={at:number;players:Map<string,Pick<P,'x'|'y'|'z'|'alive'>>};type Room={code:string;host:string;state:'LOBBY'|'PLAYING'|'GAME_OVER';players:Map<string,P>;history:History[];winner?:string;tick:number;lastStep:number};
const chars='ABCDEFGHJKMNPQRSTUVWXYZ23456789',rooms=new Map<string,Room>(),colors=[0xff4e7a,0x36d8c4,0xf7ba4b,0xa777ff,0x50a6ff,0xff6b37,0x37caff,0x92e34f],blankInput=():Input=>({seq:0,clientTime:0,moveX:0,moveY:0,lookX:0,lookY:0,jump:false}),now=()=>Date.now();
const spawn=(p:P,i:number)=>Object.assign(p,{x:ARENA_SPAWNS[i%ARENA_SPAWNS.length][0],y:1.65,z:ARENA_SPAWNS[i%ARENA_SPAWNS.length][1],velocityY:0,hp:100,alive:true,ammo:30,reserve:120,reloadUntil:0});
const publicPlayer=({input,lastShot,reloadUntil,velocityY,...p}:P)=>p;const state=(r:Room)=>({code:r.code,host:r.host,state:r.state,winner:r.winner,players:[...r.players.values()].map(publicPlayer)});const snap=(r:Room)=>({serverTime:now(),tick:r.tick,players:[...r.players.values()].map(p=>({...publicPlayer(p),ack:p.lastSeq}))});
function code():string{let s='';while(s.length<6)s+=chars[Math.floor(Math.random()*chars.length)];return rooms.has(s)?code():s}function emit(io:Server,r:Room){io.to(r.code).emit('room:state',state(r))}
function wall(a:P,d:[number,number,number],max:number){for(let t=.3;t<max;t+=.22)if(blocked(a.x+d[0]*t,a.z+d[2]*t,.04)&&a.y+d[1]*t<3)return true;return false}
function shoot(io:Server,r:Room,a:P,i:Input){const t=now();if(t-a.lastShot<95||a.ammo<=0||a.reloadUntil>t)return;a.lastShot=t;a.ammo--;const target=t-Math.max(0,Math.min(250,t-i.clientTime));let f=r.history[0];for(const h of r.history)if(h.at<=target)f=h;const d:[number,number,number]=[-Math.sin(a.yaw)*Math.cos(a.pitch),Math.sin(a.pitch),-Math.cos(a.yaw)*Math.cos(a.pitch)];let victim:P|undefined,best=Infinity;for(const p of r.players.values()){if(p.id===a.id)continue;const q=f?.players.get(p.id);if(!q?.alive)continue;const vx=q.x-a.x,vy=q.y-.35-a.y,vz=q.z-a.z,dot=vx*d[0]+vy*d[1]+vz*d[2],off=Math.hypot(vx-dot*d[0],vy-dot*d[1],vz-dot*d[2]);if(dot>0&&off<.8&&dot<best&&!wall(a,d,dot)){victim=p;best=dot}}io.to(r.code).emit('match:shot',{id:a.id,origin:[a.x,a.y,a.z],dir:d});if(!victim)return;victim.hp=Math.max(0,victim.hp-25);io.to(victim.id).emit('match:damage',{from:{x:a.x,z:a.z},hp:victim.hp,name:a.name});if(victim.hp)return;victim.alive=false;victim.deaths++;a.kills++;if(a.kills>=10){r.state='GAME_OVER';r.winner=a.name}else setTimeout(()=>{if(r.state==='PLAYING'&&!victim!.alive){spawn(victim!,[...r.players.keys()].indexOf(victim!.id));emit(io,r)}},3000);emit(io,r)}
function step(io:Server,r:Room,dt:number){if(r.state!=='PLAYING')return;const t=now();r.tick++;for(const p of r.players.values()){if(!p.alive)continue;if(p.reloadUntil&&t>=p.reloadUntil){const n=Math.min(30-p.ammo,p.reserve);p.ammo+=n;p.reserve-=n;p.reloadUntil=0}const i=p.input;stepPlayer(p,i,dt);if(i.reload&&p.ammo<30&&p.reserve>0&&!p.reloadUntil)p.reloadUntil=t+1250;if(i.shoot)shoot(io,r,p,i);p.input={...i,lookX:0,lookY:0,jump:false,shoot:false,reload:false}}r.history.push({at:t,players:new Map([...r.players].map(([id,p])=>[id,{x:p.x,y:p.y,z:p.z,alive:p.alive}]))});while(r.history[0]?.at<t-250)r.history.shift();if(r.tick%3===0)io.to(r.code).emit('match:snapshot',snap(r))}
export function createGameServer(){const app=express(),http=createServer(app),io=new Server(http,{cors:{origin:process.env.CORS_ORIGIN||'*',methods:['GET','POST']}});app.get('/health',(_,res)=>res.json({ok:true,rooms:rooms.size}));io.on('connection',s=>{let room:Room|undefined;const join=(r:Room,name:string)=>{const p:P={id:s.id,name:name.trim(),color:colors[r.players.size],x:0,y:1.65,z:0,yaw:0,pitch:0,velocityY:0,hp:100,alive:true,kills:0,deaths:0,ammo:30,reserve:120,reloadUntil:0,lastShot:0,lastSeq:0,input:blankInput()};spawn(p,r.players.size);r.players.set(s.id,p);s.join(r.code);emit(io,r)};s.on('room:create',(name:string,cb:(x:unknown)=>void)=>{if(!/^[\s\S]{2,16}$/.test(name))return cb({error:'INVALID_NICKNAME'});const c=code();room={code:c,host:s.id,state:'LOBBY',players:new Map,history:[],tick:0,lastStep:now()};rooms.set(c,room);join(room,name);cb({code:c})});s.on('room:join',(d:{code:string;name:string},cb:(x:unknown)=>void)=>{const r=rooms.get(d.code.toUpperCase());if(!r)return cb({error:'ROOM_NOT_FOUND'});if(r.players.size>=8)return cb({error:'ROOM_FULL'});if(r.state!=='LOBBY')return cb({error:'GAME_IN_PROGRESS'});room=r;join(r,d.name);cb({code:r.code})});s.on('game:start',()=>{if(!room||room.host!==s.id||room.players.size<2)return;room.state='PLAYING';room.history=[];[...room.players.values()].forEach((p,i)=>{p.kills=p.deaths=0;spawn(p,i)});emit(io,room);s.emit('match:init',{serverTime:now(),tick:room.tick})});s.on('match:input',(i:Input)=>{const p=room?.players.get(s.id);if(!p||room?.state!=='PLAYING'||!Number.isSafeInteger(i?.seq)||i.seq<=p.lastSeq)return;p.lastSeq=i.seq;p.input={...p.input,...i,moveX:Math.max(-1,Math.min(1,i.moveX||0)),moveY:Math.max(-1,Math.min(1,i.moveY||0)),lookX:Math.max(-200,Math.min(200,i.lookX||0)),lookY:Math.max(-200,Math.min(200,i.lookY||0)),clientTime:Math.max(now()-250,Math.min(now(),i.clientTime||now()))}});s.on('game:again',()=>{if(!room||room.host!==s.id||room.state!=='GAME_OVER')return;room.state='PLAYING';room.winner=undefined;[...room.players.values()].forEach((p,i)=>{p.kills=p.deaths=0;spawn(p,i)});emit(io,room)});s.on('disconnect',()=>{if(!room)return;room.players.delete(s.id);if(!room.players.size)rooms.delete(room.code);else{if(room.host===s.id)room.host=room.players.keys().next().value!;emit(io,room)}})});const timer=setInterval(()=>{const t=now();for(const r of rooms.values()){const dt=Math.min(.05,(t-r.lastStep)/1000);r.lastStep=t;step(io,r,dt)}},1000/60);return{app,http,io,close:()=>{clearInterval(timer);io.close()}}}
const game=createGameServer();game.http.listen(Number(process.env.PORT??3001),'0.0.0.0');
