import{WEAPON_IDS,WEAPON_SPECS,type WeaponId}from'../../../shared/weapons';
export class Armory{
  private open=false;private selected=0;private active:WeaponId='ar';private signature='';private box:HTMLElement;private track:HTMLElement;private coarse=matchMedia('(pointer:coarse)').matches||navigator.maxTouchPoints>0;
  private equip(id:WeaponId){if(!this.owned().has(id))return false;this.choose(id);this.active=id;this.render(id);this.close();return true;}
  private onClick=(event:Event)=>{if(!this.open)return;const card=(event.target as HTMLElement).closest<HTMLElement>('[data-armory]');if(!card&&this.coarse)return;const id=card?card.dataset.armory as WeaponId:WEAPON_IDS[this.selected],index=WEAPON_IDS.indexOf(id);if(index>=0)this.selected=index;if(!this.equip(id)){this.render(this.active);this.scrollSelected();}};
  private onWheel=(event:WheelEvent)=>{if(!this.open)return;event.preventDefault();this.move(event.deltaY>0?1:-1);};
  private onArmory=()=>this.toggle();
  private onKey=(event:KeyboardEvent)=>{if(event.key.toLowerCase()!=='q')return;event.preventDefault();this.toggle();};
  constructor(private root:HTMLElement,private choose:(id:WeaponId)=>void,private owned:()=>Set<WeaponId>,private afterClose?:()=>void){const hint=this.coarse?'左右滑動・點擊裝備':'滾輪選取・任意點擊裝備';root.insertAdjacentHTML('beforeend',`<div class="co-armory" hidden><div class="co-armory-head">武器庫 <small>${hint}</small></div><div class="co-armory-track"></div></div>`);this.box=root.querySelector('.co-armory')!;this.track=this.box.querySelector('.co-armory-track')!;this.track.innerHTML=WEAPON_IDS.map(id=>{const w=WEAPON_SPECS[id];return`<button class="co-weapon-card" data-armory="${id}" style="--weapon:#${w.color.toString(16).padStart(6,'0')}"><span>${w.icon}</span><b>${w.label}</b><small></small><em>${w.magazine} 發／∞</em></button>`;}).join('');root.addEventListener('click',this.onClick);root.addEventListener('wheel',this.onWheel,{passive:false});root.addEventListener('armory',this.onArmory);window.addEventListener('keydown',this.onKey);this.render('ar');}
  get isOpen(){return this.open;}
  close(){if(!this.open)return;this.open=false;this.box.hidden=true;this.signature='';this.afterClose?.();}
  toggle(){if(this.open){this.close();return;}this.open=true;this.box.hidden=false;const index=WEAPON_IDS.indexOf(this.active);if(index>=0)this.selected=index;this.render(this.active);this.scrollSelected(false);}
  move(delta:number){this.selected=(this.selected+delta+WEAPON_IDS.length)%WEAPON_IDS.length;this.render(this.active);this.scrollSelected();}
  render(active:WeaponId=this.active){this.active=active;this.box.hidden=!this.open;const owned=this.owned(),signature=`${this.open}|${active}|${this.selected}|${WEAPON_IDS.map(id=>owned.has(id)?1:0).join('')}`;if(signature===this.signature)return;this.signature=signature;WEAPON_IDS.forEach((id,index)=>{const card=this.track.children[index] as HTMLButtonElement,has=owned.has(id),spec=WEAPON_SPECS[id];card.classList.toggle('active',id===active);card.classList.toggle('focus',index===this.selected);card.classList.toggle('locked',!has);card.disabled=!has;(card.querySelector('small') as HTMLElement).textContent=has?spec.description:'尚未取得';});}
  private scrollSelected(smooth=true){requestAnimationFrame(()=>{(this.track.children[this.selected] as HTMLElement)?.scrollIntoView({behavior:smooth?'smooth':'auto',block:'nearest',inline:'center'});});}
  dispose(){this.root.removeEventListener('click',this.onClick);this.root.removeEventListener('wheel',this.onWheel);this.root.removeEventListener('armory',this.onArmory);window.removeEventListener('keydown',this.onKey);}
}
